### ISSUE TITLE
Make an RFC for writing compound data literals

### ISSUE THREAD

**Issue by AlexKnauth** [racket/rhombus#10]
For how to write built-in data structures with reader syntax rather than function calls. Current examples compound data literals in Racket include `#hash([a . 1] [b . 2] [c . 3])` for hash tables and `#(1 2 3)` for vectors.

Examples in other languages include `{'a 1 'b 2 'c 3}` for hash tables in Clojure, `[1 2 3]` for vectors in Clojure, `(1, 2, 3)` for tuples in Haskell, and `[1, 2, 3]` for lists is Haskell.

One thing I think should be considered is getting rid of auto-quoting in elements, and instead allowing expressions in elements. For example if `#(elem ...)` makes vectors, `#((+ 1 2))` should be equivalent to `(vector 3)` and not `(vector (list '+ 1 2))`.

**Comment by jackfirth** [comment]
Related work: Clojure's [Extensible Data Notation (EDN)](https://github.com/edn-format/edn) format.

**Comment by jeapostrophe** [comment]
A related idea is the unification of `quote` and `syntax` a la `template`

**Comment by blerner** [comment]
Also possibly related: Pyret's constructor notation (https://www.pyret.org/docs/latest/Expressions.html#%28part._s~3aconstruct-expr%29)

**Comment by jeapostrophe** [comment]
It would be beautiful for syntax templates to have the exact same syntax as the code they generate. In other words, something like

```
(syntax 1 + 1)
```

as the way to write down the syntax of `1 + 1`.

Perhaps related to #6

**Comment by mflatt** [comment]
#527
