### ISSUE TITLE
Unify srcloc

### ISSUE THREAD

**Issue by sorawee** [racket/rhombus#103]
There are multiple representations of source locations (e.g., list, vector, srcloc struct, syntax). Not all of them can be used in functions that expect "source location". For instance, datum->syntax doesn't accept srcloc struct. 

My proposal is that there should be only one canonical representation (srcloc struct in particular), but if that's not possible, every function that consumes source location should be consistent and support every representation.

**Comment by gus-massa** [comment]
A few days ago, I was surprised that there is no `syntax->srcloc` function.

**Comment by AlexKnauth** [comment]
The [`build-source-location`](https://docs.racket-lang.org/syntax/Source_Locations.html#%28def._%28%28lib._syntax%2Fsrcloc..rkt%29._build-source-location%29%29) function from `syntax/srcloc` can act as a `syntax->srcloc` function if you give it a syntax object

**Comment by mflatt** [comment]
#527
