### ISSUE TITLE
Any basic ready-to-use Rhombus yet?

### ISSUE THREAD

**Issue by datdinhquoc** [racket/rhombus#135]
Parentheses are an eyesore, is Rhombus basic code ready yet?
Can I install it to use now like Honu? So eager for having this Rhombus.

`sudo raco pkg install honu` to
`sudo raco pkg install rhombus`?

I can use `define-syntax-parser #%app` to define infix for my language, but how to get rid/reduce parentheses, I need Rhombus quick.

My wishlist: Have Rhombus quick.

**Comment by jackfirth** [comment]
You may wish to look at the current proposals for a surface syntax, such as shrubbery notation (#122) or line expressions (#114). There isn't a `#lang rhombus` available for installation yet though.

**Comment by martin12333** [comment]
@datdinhquoc you probably know about 
`
#lang sweet-exp ......
`

> The third parameter on the #lang line is the base language used by the language mixin. The resulting language will use the bindings from the base language, but support sweet expression syntax. You can provide any language here such as racket, typed/racket, or others.

**Comment by mflatt** [comment]
The `rhombus` package is ready for installation!

#527
