### ISSUE TITLE
Make a process for choosing better names throughout the language

### ISSUE THREAD

**Issue by jamesliudotcc** [racket/rhombus#141]
This issue is inspired by this [episode of Functional Geekery](https://www.functionalgeekery.com/episode-55-andreas-stefik/), where evidence based studies on what makes it difficult to learn and use programming languages was discussed.

For example, `print` doesn't make sense to people new to programming. Not that one uses `print` much in Dr. Racket. But [`car,` `cdr`](https://github.com/racket/rhombus-brainstorming/issues/21), and its kin are horrible. There is another [issue that claims `filter` is hard to understand](https://github.com/racket/rhombus-brainstorming/issues/131). But it is not as hard as `map` or `fold` or `reduce`.

Because languages tend to adopt the current terminology from other languages, I don't think that "a lot of other languages do it too" is particularly good evidence that a certain usage is ergonomic. Rather, there is some [research](http://www.cs.cmu.edu/~NatProg/programminglanguageusability/) out there about what is easy for English-speakers to understand, and even a language built out of that [research](https://quorumlanguage.com/).

**Comment by mflatt** [comment]
#527
