### ISSUE TITLE
[Syntax] Indentation - based

### ISSUE THREAD

**Issue by ShalokShalom** [racket/rhombus#142]
Hi there 🤗

1) I just saw (and see a second time) [this video.](https://youtu.be/LN0qG-i1iT0)

2) While doing so, I was looking in the internet to find some form of sweet expressions, who are maintained for Clojure or Racket.

3) At the end of the talk, the speaker mentions and shows, that there is actually one, that is proposed to be the future syntax in Racket 😊

So, I am super hyped about this and interested into some indentation based language, that has the characteristics of Racket. I personally find it very hard, to even read or write any language with symbols or keywords for delimiting, and I love the idea to bring clean, nice syntaxing to Racket.

Here my, very limited suggestions:

1) Give us the freedom to decide how many units are used to indent one block. Many languages like FSharp and Elm have made good experiences with that, Python gets often criticized for forcing people into one direction.

2) Force people into "tabs for indentation and spaces for alignment"

That second one is surely somehow controversial and my main reason to write this here. Tabs for indentation and spaces for alignment is the *only* way to check all the checkboxes in your document [here](https://github.com/racket/rhombus-brainstorming/blob/master/resources/syntax-considerations.md#considerations-list)

Another reason is that alignment and indentation is something different, so I guess different symbols for different things make sense. It gives more impression, of what is used and why, especially for beginners. It is a check, if the student has understood, what is what. Studies can be done. 

Last but not least: Thanks a ton!
Matthias

**Comment by jackfirth** [comment]
Hello! There's been a few proposals so far, but little has been finalized. See #122 for the latest iteration or #119 and #114 for previously-discussed alternatives.

**Comment by AlexKnauth** [comment]
I and other people are also working on alternatives that have a closer one-to-one correspondence with s-expressions

**Comment by mflatt** [comment]
#527
