### ISSUE TITLE
More predictable literal reading

### ISSUE THREAD

**Issue by sorawee** [racket/rhombus#145]
Currently, symbol is like an else clause in the reader. If it's not a number and not a yada yada, then it's a symbol. This makes it difficult to figure out if something is a symbol. 

Here's a fun quiz. In each item below, is it read as a symbol or a number?

- `2i`
- `+i`
- `2e5`
- `+e5`

I propose that we should have more predictable rules.

This doesn't necessarily mean we must limit to the usual `[a-zA-Z_][a-zA-Z0-9_]*`. Actually, the fact that Racket supports unicode identifiers is a huge plus for me (and I'm sad that in the current syntax proposals they will no longer be supported).

For example, one possible change is to mandate that any number literal that has a non-numeric character (except `.` and `-`, and possibly `/` and `+`?) should be prefixed by `#...`. This would make `2i`, `+i`, `2e5`, `+e5` all symbols.

**Comment by sorawee** [comment]
I guess my issue is not with how symbol is an else clause per se. It's OK to have symbol as an else clause if other clauses are simple. The problem is that they are not.

**Comment by tgbugs** [comment]
The suggestion to use `#` to clarify special cases is sort of already implemented. `#d+i` behaves as you suggest, so in theory all that would have to happen is drop the other forms. That said, there is no way you are going to convince anyone that `2e5` should read as a symbol. That is scientific notation for numbers and is extremely well established.

**Comment by slaymaker1907** [comment]
I don't think introducing a new syntax for special symbols is actually necessary. In Racket today, you can be explicit about defining symbols/identifiers using the `|id|` syntax, why not use that syntax for general symbols and identifiers?

**Comment by tgbugs** [comment]
@slaymaker1907 the question is what to do when `|id|` syntax is not used, requiring symbol literal syntax for all symbols simply isn't practical (it makes files an absolute nightmare for humans to read). We are looking for a way to regularize the behavior of reading atoms so that it is consistent, and we probably don't just want to raise a syntax error if someone accidentally hits a potentially ambiguous symbol name since it creates a nasty black hole in the grammar.

**Comment by mflatt** [comment]
#527
