### ISSUE TITLE
Make richer comparators the default

### ISSUE THREAD

**Issue by Metaxal** [racket/rhombus#149]
There seems to be a regular need for coders to define their own total/partial order comparison libraries, which at their core use comparators that return a value such as `<, >, =` (and maybe also `#f` for partial orders) instead of being based on a large set of comparison predicates such as `string<?`, `string<=?`, etc.
The claimed reasons are efficiency and flexibility.

Some Racket/Scheme examples in the wild:
* [SRFI 67](https://srfi.schemers.org/srfi-67/srfi-67.html) 
* [data/order](https://docs.racket-lang.org/data/Orders_and_Ordered_Dictionaries.html?q=data%2Forder)
* [rebellion/comparator](https://docs.racket-lang.org/rebellion/Comparators.html)
* [bazaar/order](https://github.com/Metaxal/bazaar/blob/master/order.rkt)
* [SRFI 128+162](https://srfi.schemers.org/srfi-162/srfi-162.html)
* (please let me know if you know of some more)

Comparators make it far easier to define orders on compound objects. Example from srfi/67:
```racket
  (define (box-compare box1 box2)
    (refine-compare 
      (length-compare (width  box1) (width  box2))
      (length-compare (height box1) (height box2))
      (length-compare (depth  box1) (depth  box2))))
```
(or in bazaar/order:
```racket
(define box<=>
  (make-chain<=> number<=> box-width
                 number<=> box-height
                 number<=> box-depth))
```
)

I won't advocate here for using one of these libraries in particular, but I believe Rhombus should be based on such richer comparisons.

**Comment by mflatt** [comment]
#527
