### ISSUE TITLE
improvements in object system? (CLOS)  optional first class multiple discpatch (Julia, Dylan)

### ISSUE THREAD

**Issue by bijang** [racket/rhombus#161]
reference to CLOS and smalltalk, more specifically anything to be learned and considered for new rhombus data structures, from Dylan and Julia wrt multiple-dispatch/multimethod component, see Julia's use of  multiple-dispatch as  first class component in it's data structures , is there anything to be applied or adopted here?

**Comment by mflatt** [comment]
#527
