### ISSUE TITLE
make regexes not need double escaping

### ISSUE THREAD

**Issue by spdegabrielle** [racket/rhombus#27]
make regexes not need double escaping
as described in http://www.greghendershott.com/2015/08/at-expressions.html

**Comment by sorawee** [comment]
An alternative solution is to adapt SRE by Olin Shivers (http://www.ccs.neu.edu/home/shivers/papers/sre.txt) to work with Racket's regex.

**Comment by samdphillips** [comment]
As someone who has worked with regular Racket regexp and SRE it would be great to have both.

**Comment by mflatt** [comment]
#527 

Arguably closing this early, since the regexp sublanguage is not yet merged or even in a PR. But it's claimed on the wiki page linked from  #521
