### ISSUE TITLE
Mutable vector should be growable.

### ISSUE THREAD

**Issue by spdegabrielle** [racket/rhombus#28]

**Comment by spdegabrielle** [comment]
requested by @sorawee

**Comment by sorawee** [comment]
There are two parts for this:

1. I can't think of a reason why there would be an overhead in growable vector, but if there's one, we might want to keep fixed-size vector for those who want performance. However, growable vector should be provided as the default, with a sensible name that is not `gvector`.
2. But if not, we could also just provide growable vector alone.

**Comment by rmculpepper** [comment]
I disagree. There are lots of ways that code can break if a mutable vector unexpected changes size (presumably growable vectors are also shrinkable vectors!). Such bugs and potential bugs were a major part of the reason that Racket made pairs immutable.

IMO, resizable vectors should be a conveniently-available but distinct data type.

**Comment by sorawee** [comment]
OK, I'm sold on this. But we should pick a better name than `gvector`.
