### ISSUE TITLE
Type inference 

### ISSUE THREAD

**Issue by ShalokShalom** [racket/rhombus#357]
From: **The State of Rhombus**

> Racket’s runtime contracts and Typed Racket’s static types are at two extreme ends of the dynamic-static correctness spectrum. Can Rhombus occupy a more user-friendly middle ground?

I have an idea about that. Not only SML based languages, but also dynamically typed languages [like Julia](https://docs.julialang.org/en/v1/devdocs/inference/), can have full, global type inference. 

I see the benefit in the almost completely solved question, how the heck type annotations are fitting into our current syntax. 😄 

Julia does this, by keeping the types actually in runtime, and does neat tricks with it, in conjunction with multiple dispatch. 

As many of you know, is Julia very heavily inspired by Lisp, and has its current parser even implemented in a [custom Scheme](https://github.com/JeffBezanson/femtolisp). 

I assume, due to the way this is implemented, that this exceeds the scope of this project. 
But I also assume, that it would provide a neat way, to what otherwise seems to lead nearly unavoidably to chaos. 

In case somebody is interested about a [list of languages who have full type inference,](https://gist.github.com/ShalokShalom/af804bee1822a22f98ad6b25ce73492c) be my guest. 

Julia serves as a perfect example, due to its familiarity and implementation of a dynamic type system.

**Comment by mflatt** [comment]
#527 

There's a lot more to be done/said about the spectrum of static information and types in Rhombus. But for now, the choices for `#lang rhombus` seem in place.
