### ISSUE TITLE
include pattern matching forms in more binding positions

### ISSUE THREAD

**Issue by spdegabrielle** [racket/rhombus#36]
include pattern matching forms in more binding positions (e.g. `define`, `let`/`for` clauses) - 
@samth  2 Oct 2012

**Comment by AlexKnauth** [comment]
Cross-reference with point (4) of #23, since the syntax of patterns affects whether they can be used unambiguously in things like optional-arguments with defaults, as @dedbox pointed out

**Comment by rocketnia** [comment]
If `syntax-parse` is merged with matching and matching is used for argument lists, then I think the syntax would change in a way that's something like this:

```racket
; before
(define (my-print [out (current-output-port)])
  ...)

; after
(define (my-print {~optional out #:defaults ([out (current-output-port)])})
  ...)

; after defining a `define-splicing-syntax-class` helper
; (or maybe it would be `define-splicing-class`)
(define (my-print {~opt out (current-output-port)})
  ...)
```

The ambiguity would have come from the original syntax's use of parens without a prefix operator inside them. The revision just adds `~opt` to keep it clear why the parens are there.

**Comment by dedbox** [comment]
While I agree a pattern-friendly syntax for args with defaults would be good, I think making match patterns appear more like syntax patterns would be a mistake unless we also intend to unify the semantics (and consequent developer experience) of expansion and evaluation. See #23 for my rationale.

**Comment by mflatt** [comment]
#527
