### ISSUE TITLE
Make an RFC for supporting define* in internal-definition context

### ISSUE THREAD

**Issue by sorawee** [racket/rhombus#46]
Originally from @jeapostrophe 

> Enable the racket/package define* form everywhere

Personally, I use `define` in internal-definition context a lot. In most cases, however, I don't want `letrec`, but just want `let`. The reason I didn't use `let` is that I want to avoid excessive indentation.

But there are cases that `define` doesn't work well as a replacement for `let`. E.g., 

```
(define (f x)
  (define x (max x 0))
  (* x x))
```

vs

```
(define (f x)
  (let ([x (max x 0)])
    (* x x)))
```

It would be nice if we can write:

```
(define (f x)
  (define* x (max x 0))
  (* x x))
```

which effectively transforms the code into the latter one. Note that it shouldn't require a wrapper macro like `package-begin` over `define*`.

`define-values`/`match-define`/`match-define-values` counterparts should be provided as well.

**Comment by gus-massa** [comment]
I like shadowing a lot, so I agree with this.

**Comment by sorawee** [comment]
We might want to pick a shorter name. I imagine this `define*` will replace most usage of `let` forms.

**Comment by jackfirth** [comment]
Does it have to be distinct from `define`? Could `define` just do this by default?

**Comment by sorawee** [comment]
It needs to be distinct from `define` because `define` allows defining recursive functions (`letrec` semantics), but this one has the semantics of `let*` which does not.

**Comment by jackfirth** [comment]
Hmm. What if `define` did this by default when defining _constants_, but not when defining functions? Plus maybe some optional keyword or annotation when you want to be explicit whether a definition is shadowing or not.

**Comment by sorawee** [comment]
> Hmm. What if `define` did this by default when defining _constants_, but not when defining functions? 

IMO, context-sensitive constructs are error prone. I would avoid them.

**Comment by jackfirth** [comment]
I'm not sure that counts as context-sensitive. Whether or not a `define` behaves like `let*` or `letrec` would depend purely on the shape of the `define` itself, not on the context surrounding it.

I think adding variations of `define` with different names would have a usability cost. Right now we can get away with a single `define` form for everything from defining functions to module-level constants to local variables, and I personally don't even find myself using any of the `let` forms (instead I use `cond` and internal definitions). I'd hate to give that simplicity up.

**Comment by gus-massa** [comment]
What about this examples?

    (define f 0)
    (define (f x) (list x f))
    (define f (lambda (x) (list x f)))

**Comment by mflatt** [comment]
#527
