### ISSUE TITLE
Change integer? to mean exact-integer?

### ISSUE THREAD

**Issue by gus-massa** [racket/rhombus#52]
* Change `integer?` to mean `exact-integer?`.

Extracted from the old racket2 wiki. https://github.com/racket/racket2-rfcs/issues/33

If the old `integer?` primitive were removed, how hard is to write it in racket1/racket2? Floating point calculations are sometime more tricky than expected. 

(Perhaps we can collect here some similar renaming in the numerical tower.)

**Comment by mflatt** [comment]
#527
