### ISSUE TITLE
DrRacket REPL hangs reading Racket escaped symbol

### ISSUE THREAD

**Issue by samdphillips** [racket/rhombus#541]
In the DrRacket REPL reading this symbol does not work.  When the same characters are in the definitions pane the module executes correctly.  This also works properly in the expeditor REPL.

```
> #'#{+}
. . projects/contrib/rhombus/shrubbery-lib/shrubbery/lex.rkt:1265:0: user break
```

**Comment by mflatt** [comment]
Repaired by racket/racket@b35914f99fdb7ebb2e20dbe73252389b2afc0186.
