### ISSUE TITLE
Make an RFC about structs lack of hygiene

### ISSUE THREAD

**Issue by jeapostrophe** [racket/rhombus#57]
In Racket1, `struct` defines multiple names. I'd like Racket2's `struct`-like thing to just define a single name and provide the accessors, mutators, etc via some other mechanism.

For example, in Remix, the struct name is a single `define-syntax` binding that is a struct that implements a bunch of generic interfaces, including a `#%dot` transformer that exposes fields and other stuff. I don't think that Racket2 needs to do it this way, but something like that would be nice. At the very least, the static information about a struct should allow you to discover all of the fields, so something like `struct-copy` (if it weren't built in better) wouldn't have to be a hack.

**Comment by sorawee** [comment]
Note that adding static information about fields is possible in Racket 1 already (see the discussion at #2700)

While I like `<obj>.<fieldname>` in various languages because it doesn't clutter namespace with accessors, these accessors can prevent certain bugs. For example, it's possible to make a typo and only discover the problem at runtime (`obj.fieldnamee` instead of `obj.fieldname`), but with accessors, we will get unbound id error at compile time.

**Comment by jeapostrophe** [comment]
Remix gives unbound id errors at compile time for situations like this. `obj.fieldname` does not need to be `dict-ref obj 'fieldname`. In Remix, it expands to `(#%dot obj fieldname)` and if `obj` is bound to a `dot-transformer` it can expand itself (if it isn't, then it does expand to `(dot-ref obj 'fieldname)`). The dot transformer that `struct` produces has a fixed set of valid fields and expands to the underlying real accessor.

**Comment by sorawee** [comment]
I should read about Remix, but in general we can't know static information about `obj` unless we have type checking, correct?

**Comment by jeapostrophe** [comment]
Incorrect, the static information could be part of the identifier binding via `syntax-local-value`. Again, in Remix, when you write something like `(def (f [posn p]) (+ p.x 1))` the `posn` def-transformer binds `p` as a dot-transformer that expands `p.x` (i.e. `(#%dot p x)`) into `(posn-x p)` --- all at compile time without general type checking. Obviously this breaks down if the structure is the result of another expression. However, I think we should be comfortable with Racket2 having some built-in machinery in the standard library to do local Turnstile-style communication of syntax properties such as this; both for doing compile-time checking for things like this, but there's presumably a larger number of useful things to infer.

**Comment by mflatt** [comment]
#527
