### ISSUE TITLE
Ensure early-on the existence of a comprehensive testsuite and benchmark suite

### ISSUE THREAD

**Issue by pmatos** [racket/rhombus#58]
It is extremelly important as we start a new language that will hopefully be here to stay to create a testsuite and benchmark suite. Possibly start with a testsuite and get to more complex programs to use as benchmarks later.

Once we get a few examples of what we want going we can use those as initial tests.

**Comment by spdegabrielle** [comment]
I’d suggest RFC’s should come with tests/examples. 

e.g.
```
<repo>/0001-my-feature/0001-my-feature.md
<repo>/0001-my-feature/test001.rk2
```

**Comment by mflatt** [comment]
#527
