### ISSUE TITLE
Provide Racket2 with some form of a gradual or static type system

### ISSUE THREAD

**Issue by mguimas** [racket/rhombus#59]
Is there any plans to make Typed Racked the default base for Racket 2? 

I mean, whatever Racket 2 will be, will it have the type system of Typed Racket?

Or more generally, will it come with some form of a gradually or statically typed type system? 

Or is Racket 2 only planning for the "syntax revolution”?

I am very used to dynamic typing, but changes tend to slow down for large codebases because of the time needed to get types right. A statically typed system would avoid all this by quicklly pinpointing where are the type mismatches. In fact, almost all my errors are type errors, not logic errors.

A typed Racket 2 would thus be very productive language with this regard.

Thanks

**Comment by spdegabrielle** [comment]
relevant:
 [The Laffer Curve of Types](https://felleisen.org/matthias/Thoughts/The_Laffer_Curve_of_Types.html) by @mfelleisen

**Comment by jeapostrophe** [comment]
I think it would be very valuable to have something like Typed Racket but more gradual in Racket2. A situation where you could slowly add the necessary annotations and get something even when the program doesn't type check, like the static knowledge of valid fields mentioned in #57

**Comment by mguimas** [comment]
This link might be interesting [Typer: an infix statically typed Lisp](https://icfp17.sigplan.org/details/mlfamilyworkshop-2017-papers/4/Typer-an-infix-statically-typed-Lisp)

**Comment by elfprince13** [comment]
I mentioned this on the mailing list, but I would *really* like to see Racket2 be statically typed, with opt-in affine-types allowing code to be "gradually resource aware".

**Comment by jackfirth** [comment]
Relevant work linked to in the Laffer Curve of Types post: [progressive type systems](http://cs.brown.edu/research/plt/dl/progressive-types/progressive-types.pdf).

**Comment by mflatt** [comment]
#527 

There's still a lot to be said and done in the spectrum of static information, but the direction for `#lang rhombus` (and `#lang rhombus/static`) seems set.
