### ISSUE TITLE
[wishlist] Make Matthew's doc-define from ClojureWest keynote real

### ISSUE THREAD

**Issue by spdegabrielle** [racket/rhombus#60]
from Wishlist of backwards incompatible things for a future Racket2. #33

**Comment by pmatos** [comment]
Is there a link to this reference/video?

**Comment by sorawee** [comment]
I think it refers to slide 149 at https://raw.githubusercontent.com/strangeloop/clojurewest2013/master/slides/sessions/Flatt-MetaprogrammingTime.pdf

**Comment by spdegabrielle** [comment]
slide 149:

**In-Source Scribble Documentation**

![Screenshot 2019-07-24 at 19 42 04](https://user-images.githubusercontent.com/108047/61819557-2e0e9a80-ae4b-11e9-98ca-770b64aa1e6b.png)

**Comment by vityou** [comment]
One thing I like about python is it's docstring system and `help` function.  Scribble is great for documenting a library, but not so great for describing helper functions in a file that don't get exported.  Most people just use comments, but we may benefit from having a more standard way of describing functions, perhaps available at runtime with something similar to `help`.  I would enjoy having a tooltip pop up for a function, even one in the same file.  Using scribble may be difficult for supporting tooltips (maybe), so maybe there could be a simple docstring in source, while scribble maintains it's html based interface with the user.

**Comment by benknoble** [comment]
Clojure's define forms allow arbitrary metadata to be attached to a symbol in a map: if racket and/or rhombus had something similar, it could be used for standard things (docs, types, contracts, what have you) and also for more interesting things (which I have not dreamt of).

**Comment by diego-crespo** [comment]
If we use scribble would that mean it would be possible to have executable code blocks within the documentation like Rust's [Documentation tests](https://doc.rust-lang.org/rustdoc/documentation-tests.html)? If so I think that would be great for the same reasons outlined on that page.

**Comment by mflatt** [comment]
#527 

Started with some `~doc` support, at least. This task is large open-ended, but we've picked a direction for the foreseeable future.
