### ISSUE TITLE
Consider having real identifiers for class/object members and use the module/namespace mechanisms to manage these references

### ISSUE THREAD

**Issue by spdegabrielle** [racket/rhombus#61]
Consider having real identifiers for class/object members and use the module/namespace mechanisms to manage these references. Possibly in conjunction with a convention for names that are prefixed or included in others (so that we can have identifiers like `frame%:show` treated specially). Potentially makes method invocation faster and allows static detection of method-not-found errors.

from Wishlist of backwards incompatible things for a future Racket2. #33

**Comment by mflatt** [comment]
#527
