### ISSUE TITLE
Enable internal definitions everywhere.

### ISSUE THREAD

**Issue by spdegabrielle** [racket/rhombus#63]
Enable internal definitions everywhere.  (Note: this is tricky -- what's "everywhere"?
  Eg, can `define id` be followed by a definition(s) and then a value?  How about in the middle
  of an `if`?  Taken to an extreme, could definitions appear in an application form?)

from Wishlist of backwards incompatible things for a future Racket2. #33

**Comment by gus-massa** [comment]
Related: "Support `define*` in internal-definition context" https://github.com/racket/racket2-rfcs/issues/46

**Comment by mflatt** [comment]
#527
