### ISSUE TITLE
change syntax-case to allow internal definitions 

### ISSUE THREAD

**Issue by spdegabrielle** [racket/rhombus#64]
change syntax-case to allow internal definitions (possibly by getting rid of the 'guard' section)

from Wishlist of backwards incompatible things for a future Racket2. #33

**Comment by jackfirth** [comment]
What if we just got rid of `syntax-case` altogether?

**Comment by sorawee** [comment]
I think it still makes sense to have `syntax-case` for low-level core libraries, and it could even be exported in a way that discourages its use. 

Another thing that people tend to forget when using `syntax-case` (and even `syntax-parse`!) is tracking `disappeared-use`. It might make sense to have `#:track-literals` on by default for `syntax-parse`, and it must be opt-out if users don't want it.

**Comment by mflatt** [comment]
#527
