### ISSUE TITLE
Use keywords in more places, such as unifying `member`, `memv`, `memf`, etc.

### ISSUE THREAD

**Issue by spdegabrielle** [racket/rhombus#65]
Use keywords in more places, such as unifying `member`, `memv`, `memf`, etc.

from Wishlist of backwards incompatible things for a future Racket2. #33

**Comment by jackfirth** [comment]
While we're at it, can we just change the name of `member` to something like `contains?` and make it return a boolean? It's a confusing name with a confusing return value.

This is also related to #16, since getting rid of equality operators might remove the need for some of these functions.

**Comment by mflatt** [comment]
#527
