### ISSUE TITLE
Disallow mutation of `struct` bindings.

### ISSUE THREAD

**Issue by spdegabrielle** [racket/rhombus#69]
Disallow mutation of `struct` bindings.

from #33

**Comment by sorawee** [comment]
@mflatt as I understand you added this entry. What's the alternative for this then? Using `box` explicitly?

**Comment by mflatt** [comment]
Probably it's not clear that this isn't about struct fields. The idea is that if you have a struct declaration
```
(struct posn (x y))
```
then a later
```
(set! posn? 'not-the-predicate)
```
should be a syntax error. That is, the names bound by `struct` should be immutable even if struct instances are mutable.

**Comment by mflatt** [comment]
#527
