### ISSUE TITLE
Reconsider printing and equality of mutable and immutable variants of data types

### ISSUE THREAD

**Issue by spdegabrielle** [racket/rhombus#73]
> Reconsider printing and equality of mutable and immutable variants of data types (vectors,
  hash tables, strings, etc.). Also reconsider the coercion of mutable vectors to immutable
  vectors by `datum->syntax`.

from #33

**Comment by mflatt** [comment]
Done: Rhombus default equality is `equal-always?`, the `is_now` operator is available when you still want `equal?`, and printing always shows mutable and immutable values in different forms.
