### ISSUE TITLE
Make an RFC about unifying structs and classes

### ISSUE THREAD

**Issue by jeapostrophe** [racket/rhombus#76]
At a simple level, structs in Racket are just like structs in C and classes in Racket are like classes in Java. At this level, structs feel very "light" and classes feel very "heavy"---both on a syntactic and semantic.

I think that using Racket classes feels like programming in Java and it feels extremely slow and obtuse, so Racket programs with classes (outside of the GUI system) are pretty rare. I think that this feeling of heaviness has caused many Racket programs to extend and extend structs so they are much more like a unique class-system that is Racket-specific rather than an imitation of Java with lots of clever tweaks and extensions (my uncharitable description of `racket/class`.)

In this Racket-specific class system, a class (struct) is a layout and a set of interface implementations (struct properties). Classes never have their own unique methods, but always implement some predefined interface. I think that we should fully adopt this way of thinking about what structs are and in Racket2 just call them classes.

Instead of writing:

```
(struct posn (x y)
  #:methods gen:drawable
  [(define (draw me dc)
     (match-define (posn x y) me)
     (send dc draw-circle x y "solid" "blue"))]
  #:methods gen:custom-write
  [(define (write-proc me port mode)
     (match-define (posn x y) me)
     (fprintf port "(~a,~a)" x y))])
```

We should write:

```
class posn {
  x; y;

  drawable {
    draw(dc) {
      dc.draw_circle(x, y, "solid", "blue"); } }

  writable {
    write(port) {
      fprintf(port, "(~a, ~a)", x, y); } } }
```

I think it would be valuable to think about stripping structs of all of their interesting behavior and supporting more low-level "layouts" that control representations like this. Concretely, this would be something more like `define-cstruct`

Related to #57

**Comment by Metaxal** [comment]
Agree to that. Also, while unifying the two, I'd like structs/classes to start with a capital, as a distinguishing feature. This would help readability of source code.

**Comment by mflatt** [comment]
#527
